# --------------------------------------------------
# Black formatter configuration
[tool.black]
target-version = ["py313"]
include = '\.pyi?$'
extend-exclude = '''
/(
    \.git
  | build
  | dist
  | .*/static
  | .*/media
  | .*/migrations
)/
'''


# --------------------------------------------------

# isort configuration
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
known_django = ["django"]
sections = [
    "FUTURE",
    "STDLIB",
    "DJANGO",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
skip = ["migrations"]

# --------------------------------------------------

# Flake8 configuration
[tool.flake8]
max-line-length = 88
max-complexity = 10
count = true
extend-ignore = [
    "E203", # Whitespace before ':'
    "W503", # Line break before binary operator
    "E501", # Line too long
]
extend-exclude = ["*/migrations/", "*/static/", "*/media/", ".git"]
