"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import dj_database_url
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables into this "app_env" variable
app_env = environ.Env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = app_env.str("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = app_env.bool("DJANGO_DEBUG", default=False)

# A list of strings representing the host/domain names that this Django site can serve.
# See https://docs.djangoproject.com/en/5.2/ref/settings/#allowed-hosts
ALLOWED_HOSTS = app_env.list("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party apps:
    "rest_framework",
    "djoser",
    "corsheaders",  # django-cors-headers
    "drf_spectacular",
    # local apps:
    "app.account.apps.AccountConfig",
    "app.category.apps.CategoryConfig",
    "app.document.apps.DocumentConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # https://pypi.org/project/django-cors-headers/
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        engine="django.db.backends.postgresql",
        env="DJANGO_DATABASE_URL",
        conn_health_checks=True,
        conn_max_age=900,  # (900 seconds = 15 minutes)
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-LANGUAGE_CODE
LANGUAGE_CODE = app_env.str("DJANGO_LANGUAGE_CODE", default="en-us")

# List of time zones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-TIME_ZONE
TIME_ZONE = app_env.str("DJANGO_TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# If the request URL doesn't match any of the patterns in the URLconf and it doesn’t end in a slash,
# an HTTP redirect is issued to the same URL with a slash appended.
# See https://docs.djangoproject.com/en/5.2/ref/settings/#append-slash
APPEND_SLASH = True


# The model to use to represent a User.
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-AUTH_USER_MODEL
AUTH_USER_MODEL = "account.UserAccount"


# Configuration for REST framework
# See https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
}


# Configuration for DRF Spectacular
# See https://drf-spectacular.readthedocs.io/en/latest/settings.html
SPECTACULAR_SETTINGS = {
    "TITLE": "E-document API",
    "DESCRIPTION": "Detailed information about E-document web application API (also known this as the Back-end of E-document web application)",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


# Configuration for Session
# See https://docs.djangoproject.com/en/5.2/topics/http/sessions/

# Expire the session when the user closes their browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True


# CORS Headers configuration settings
# See https://pypi.org/project/django-cors-headers/
CORS_ALLOW_ALL_ORIGINS = app_env.bool("DJANGO_CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOW_CREDENTIALS = app_env.bool("DJANGO_CORS_ALLOW_CREDENTIALS", default=True)
CORS_ALLOWED_ORIGINS = app_env.list("DJANGO_CORS_ALLOWED_ORIGINS", default=[])
